### PR TITLE
Add support for immutable ordered maps in path declaration

### PR DESCRIPTION
**Pull request by gabrielmontagne**
... backwards compatible.  :pineapple:

### CODE REVIEW

**Comment by gabrielmontagne** [comment]
Fixes #7

**Comment by cristiano-belloni** [comment]
So `List(OrderedMap(...))` is for backwards compatibility, right? This means users can specify an array or an objects and get the ordered / unordered behaviour indifferently?

**Comment by cristiano-belloni** [comment]
...so that the new way of specifying routes should be like:

```javascript
[
  ['/path1/:caballo', () => ...],
  [''/path1/:vivo', (0 => ...]
]
```
We should probably document it (or have it in the reference app for now?)
 👍

**Comment by gabrielmontagne** [comment]
You can even pass it an OrderedMap if you have it.
`pathToIntent(thatOrderedMap`, etc.

**Comment by gabrielmontagne** [comment]
I have a version of the doodle app with that, but first I merged the link to the npm version so we'd need to release first if we want to keep the thing alive.   might do that now.

**Pull request merged**
