### PR TITLE
store operator

### PR DESCRIPTION
**Pull request by cristiano-belloni**
This is something that I had always wanted to do, transforming our boilerplate store code into an operator.
The only doubt is the fact that sometimes we `catchError` early in the store, but I guess that catching it immediately below the `createStore$` invocation won't make a difference?
I could have put it in the operator, but I didn't want to force what we do in case of uncaught errors inside caballo-vivo.
Ah, and I added `.prettierc` for us common mortals using VS Code 👎

### CODE REVIEW

**Comment by cristiano-belloni** [comment]
(however: this is intended as a helper operator. Users can still write their wonderful stores if `createStore$` doesn't cut it for them. It's just that we reuse the same code pretty much everywhere and `createStore$` is a bit more informative to the reader rather than scanning, removing dups and sharing)

**Comment by cristiano-belloni** [comment]
Hi! Didn't see this thread during the weekend!

> I like to see that the store is nothing magica, but 3 lines of RX

That's a good point, and I agree on that. Maybe we want to show how simple the store engine is in the docs but then expose the operator to make everything more compact? I'd like to have an example where we just create the location and the store and we're all set.

> Shall we make this a native operator?

What do you mean by "native"? I think it as a factory that returns a pipable operator because of the initial value (can't just be a pipable because of that)

> the empty map could be a default

Agreed.

> reduceStore as operator... maybe even without the $, as it is an operator? 

Agreed, but as per my previous point it should be `createReduceStore` (but probably it's me not understanding your comment and continuing not understanding it :) )

**Comment by cristiano-belloni** [comment]
(Something like this?)

```javascript
import { scan } from 'rxjs/operators'
import { Map } from 'immutable'
import shareLast from './share-last'
import distinctUntilChanged from './distinct-until-changed'

export default function createReducerStore$(initialValue = Map()) {
  return function store(source$) {
    return source$.pipe(
      scan((state, changeFn) => changeFn(state), initialValue),
      distinctUntilChanged((s1, s2) => s1.equals(s2)),
      shareLast
    )
  }
}
```

**Comment by gabrielmontagne** [comment]
@cristiano-belloni , man, I think what we sould is pair on this after work :-)  Like in the good not-so-old days :-)   Le's find a nice way to share the screen, and get on a call.

**Pull request merged**
